 "use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import Leaderboard,{Player} from "@/components/Leaderboard";
import {EVENTS} from "@/lib/events";

export default function HostGame(){
 const {code}=useParams<{code:string}>(); const router=useRouter(); const [token,setToken]=useState(""); const [game,setGame]=useState<any>(null); const [players,setPlayers]=useState<Player[]>([]); const [busy,setBusy]=useState(false); const [err,setErr]=useState("");
 async function load(){try{const r=await fetch(`/api/game/${code}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setGame(d.game);const pr=await fetch(`/api/game/${code}/players`,{cache:"no-store"});const pd=await pr.json();if(pr.ok)setPlayers(pd.players||[])}catch(e:any){setErr(e.message)}}
 useEffect(()=>{const raw=sessionStorage.getItem("throwback_host");if(!raw){router.replace("/host");return}const h=JSON.parse(raw);if(h.code!==code){router.replace("/host");return}setToken(h.token);load();const iv=setInterval(load,1000);return()=>clearInterval(iv)},[code]);
 async function action(path:string){setBusy(true);setErr("");try{const r=await fetch(`/api/game/${code}/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({hostToken:token})});const d=await r.json();if(!r.ok)throw new Error(d.error);load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const round=game?.current_round??0; const ev=EVENTS[round]; const isLobby=game?.status==="lobby"; const isFinished=game?.status==="finished";
 return <main className="tb-shell"><div className="tb-wrap"><div className="tb-brand"><a className="tb-logo" href="/">THROW<span>BACK</span></a><div className="tb-pill">HOST · {code}</div></div>
 <div className="tb-hostgrid"><section className="tb-card tb-center"><div className="tb-label">GAME CODE</div><div className="tb-code">{code}</div>{isLobby?<><h1 className="tb-title">Waiting for players</h1><div className="tb-stat">{players.length}</div><p className="tb-sub">Players can join at the game URL using this code.</p><button className="tb-btn primary big" onClick={()=>action("start")} disabled={busy||players.length===0}>{busy?"STARTING…":"START GAME"}</button></>:isFinished?<><div className="tb-finished">GAME OVER</div><p className="tb-sub">Final scores</p><Leaderboard players={players}/><a className="tb-btn primary" href="/">NEW GAME</a></>:<><div className="tb-status">Round {round+1} / 10 · {game?.status}</div><img src={ev.image} alt={ev.description} style={{width:"100%",maxHeight:300,objectFit:"contain",background:"#03060c",marginTop:16,borderRadius:12}}/><h2 style={{fontSize:22,margin:"18px 0 5px"}}>{ev.title}</h2><div style={{fontSize:44,fontWeight:950,color:"var(--accent)"}}>{ev.year}</div><p className="tb-note">Keep this screen on the projector. Players only see the image and slider.</p>{round<9?<button className="tb-btn primary big" onClick={()=>action("next")} disabled={busy}>{busy?"LOADING…":"NEXT ROUND"}</button>:<button className="tb-btn primary big" onClick={()=>action("next")} disabled={busy}>END GAME</button>}</>}</section>
 <aside className="tb-card"><Leaderboard players={players}/><div style={{marginTop:22}}><h3>Players</h3><div className="tb-players">{players.map(p=><div className="tb-player" key={p.id}>{p.name}</div>)}</div></div>{err&&<p style={{color:"var(--danger)"}}>{err}</p>}</aside></div>
 <div className="tb-card" style={{marginTop:18}}><h3>How to run the event</h3><p className="tb-note">1. Put this host page on the projector. 2. Tell everyone to open your Vercel URL and choose JOIN A GAME. 3. Display the code above. 4. Start when everyone is in. 5. After the 15-second round, wait for the answer/reveal to settle, then press NEXT ROUND.</p></div>
 </div></main>;
}